### ISSUE TITLE
Is there any reason why we flatten the output in NeuralNet.py

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#29]
Is there any reason why we flatten the output? When do classification, the predictions for multi-classes are also flattened. 

Here is the code that I am talking about in NeuralNet.py:
`!             #data['outputs']  = np.array(data['outputs']).flatten()
!             #data['targets']  = np.array(data['targets']).flatten()`

**Comment by NicoRenaud** [comment]
that's just for storage so that we can plot the data or save it in the hdf5 file. Before we flatten the data aare store as list of list where each batch is store in one of the sublist i.e. : [  [data_batch_1], [data_batch_2], ....  ].  It's more practical to have one 1D array instead of a list of list hence we flatten it

**Comment by NicoRenaud** [comment]
Got your point now ! If we do the same for the classification that's not very convenient. We flatten the data only in _plot_scatter() and we don't do it _plot_box_plot(). That's more flexible like that.
