### ISSUE TITLE
'targets' and 'i-RMSD' of the premap BM5 data are not consistent

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#86]
According to 'i-RMSD' -> num of hits for Train: 5992 out of 84557 models
According to 'i-RMSD' -> num of hits for Valid: 1944 out of 26894 models
According to 'i-RMSD' -> num of hits for Test: 2032 out of 27948 models

According to 'targets' -> num of hits for Train: 57 out of 84557 models
According to 'targets' -> num of hits for Valid: 14 out of 26894 models
According to 'targets' -> num of hits for Test: 18 out of 27948 models

**Comment by NicoRenaud** [comment]
Well it’s not really  a bug. The bin class is 1 if it’s a native i.e expérimental conformation and 0 if it’s generated by haddock or something else. It would be strange to hard code the value depending the irmsd since different threshold can be used

**Comment by NicoRenaud** [comment]
we could define a new target type like : `target='irmsd<4'` that would process the string and define the binary class accordingly. I would much prefer something like that than changing the definition of the bin class since I think Cunlinang is using the bin class target for deepface. Plus we coulde fine the the threshold freely for each experiment

**Comment by LilySnow** [comment]
Sorry, I did not describe all details. Yes, I used `target='irmsd<4'` when I generate the data on cartesius. But I do not know what happened in the middle that the target values are now incorrect (the copy that I transferred to alembick is correct though). I am correcting the data on cartesius.

**Comment by LilySnow** [comment]
I corrected the BIN_CLASS. `target = 'irmsd<=4' now.
